spring:
  application:
    name: nextera-order
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        namespace: 253e9832-53e9-43eb-bfae-4c311a7ce0fa
        group: DEFAULT_GROUP

      config:
        import-check:
          enabled: false
        server-addr: localhost:8848
        namespace: 253e9832-53e9-43eb-bfae-4c311a7ce0fa
        group: DEFAULT_GROUP
        file-extension: yml
        enabled: true
        refresh-enabled: true
        shared-configs:
          - nextera-common.yml
  # 重要配置
  config:
    import:
      - optional:nacos:nextera-common.yml
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
  nacos:
    config:
      import-check:
        enabled: true

  # ElasticSearch配置
  elasticsearch:
    uris: http://localhost:9200
    username: 
    password: 
    connection-timeout: 10s
    socket-timeout: 30s

# ElasticSearch功能开关（设置为false以禁用ElasticSearch功能）
elasticsearch:
  enabled: true


# RocketMQ功能开关（设置为false以禁用RocketMQ功能）
rocketmq:
  enabled: true
  name-server: localhost:9876
  producer:
    group: nextera-order-producer-group
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: true
    access-key: 
    secret-key: 
  consumer:
    group: nextera-order-consumer-group
    consume-timeout: 15000
    max-reconsume-times: 16
    access-key: 
    secret-key:

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 20
        min-idle: 5
