server:
  port: 7083

spring:
  application:
    name: nextera-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nextera_auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: nextera123
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms


# JWT配置
nextera:
  jwt:
    secret: nextera-framework-jwt-secret-key-2025
    expiration: 24
    refresh-expiration: 7

# 日志配置
logging:
  level:
    com.nextera: debug
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Nextera认证服务API
    description: "认证服务API文档"
    version: 1.0.0
    group:
      default:
        group-name: 认证服务
        api-rule: package
        api-rule-resources:
          - com.nextera.auth.controller