server:
  port: 7081

spring:
  application:
    name: nextera-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nextera_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: nextera123
  redis:
    host: localhost
    port: 6379
    database: 1
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# Dubbo配置
dubbo:
  application:
    name: dubbo-nextera-user
  protocol:
    host: 192.168.56.1
    name: dubbo
    port: 20881
  registry:
    address: nacos://localhost:8848?namespace=253e9832-53e9-43eb-bfae-4c311a7ce0fa&group=DEFAULT_GROUP
    username: nacos
    password: nacos
  provider:
    timeout: 5000
    retries: 0
  consumer:
    timeout: 5000
    retries: 0
    # 在全局消费者级别排除Seata相关过滤器
    filter: "-seataTransactionPropagation,-seata"

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# OpenFeign配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true

# 日志配置
logging:
  level:
    com.nextera: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always


# 文章服务配置
article:
  service:
    url: http://localhost:7082
# Seata分布式事务配置
seata:
  enabled: true
  application-id: nextera-user
  tx-service-group: nextera-user-group
  enable-auto-data-source-proxy: true
  use-jdk-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 77f5f735-c4e7-4ae2-bb52-458170479bca
      group: SEATA_GROUP
      dataId: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: 77f5f735-c4e7-4ae2-bb52-458170479bca
      group: SEATA_GROUP
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      default_tx_group: default
      nextera-article-group: default
      nextera-user-group: default

tcc:
  retry:
    # 是否启用重试控制，默认为true
    enabled: true
    # 最大重试次数，默认为3次
    max-retry-count: 3
    # 重试间隔时间（毫秒），默认1秒
    retry-interval: 1000
# service:
#   vgroupMapping: nextera-user-group

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Nextera用户服务API
    description: "用户服务API文档"
    version: 1.0.0
    group:
      default:
        group-name: 用户服务
        api-rule: package
        api-rule-resources:
          - com.nextera.user.controller


# RocketMQ配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}_PRODUCER_GROUP
    send-message-timeout: 30000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
    max-message-size: 4194304
    compress-message-body-threshold: 4096
    retry-another-broker-when-not-store-ok: true
  consumer:
    pull-batch-size: 32