spring:
  application:
    name: nextera-article
  


  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: nextera
        group: DEFAULT_GROUP
        service: ${spring.application.name}
      config:
        server-addr: localhost:8848
        namespace: nextera
        group: DEFAULT_GROUP
        file-extension: yml





# 日志配置
logging:
  level:
    com.nextera.article.mapper: debug
    org.apache.dubbo: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# 监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Knife4j配置
knife4j:
  enable: true
  openapi:
    title: Nextera Article API
    description: 文章服务API文档
    version: 1.0.0
    contact:
      name: Nextera Team
      email: admin@nextera.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
  setting:
    language: zh_cn
